### ISSUE TITLE
Feedback on /installation-guides/ubuntu/ubuntu-bionic.html

### ISSUE THREAD

**Issue by alexey-belyakov** [intel-gpu/documentation#1]
E: Unable to locate package libigc-dev
E: Unable to locate package libigdfcl-dev
E: Unable to locate package libigfxcmrt-dev
E: Unable to locate package level-zero-dev

**Comment by ketrintel** [comment]
I updated the list of packages for 18.04; it looks like there was a copy/paste from the 20.04 instructions. The available development packages for 18.04 can be installed via:

```bash
sudo apt-get install \
  intel-igc-opencl-devel \
  level-zero-devel
```
