### ISSUE TITLE
Feedback on technologies/level-zero.html

### ISSUE THREAD

**Issue by MikeSmirnov** [intel-gpu/documentation#10]
Install the development repository Ubuntu 20.04 . Link is broken.

**Comment by ketrintel** [comment]
Thanks for letting us know -- it looks like all the guide links are going to pages without "index.html"

We'll get the links updated to:

https://dgpu-docs.intel.com/installation-guides/redhat/index.html
https://dgpu-docs.intel.com/installation-guides/suse/index.html
https://dgpu-docs.intel.com/installation-guides/ubuntu/index.html

Cheers,
James

**Comment by pepla** [comment]
@MikeSmirnov - change is checked in and waiting for publishing.

**Comment by pepla** [comment]
Changes were posted and links are fixed. https://dgpu-docs.intel.com/
Closing this issue.
