### ISSUE TITLE
Feedback on installation-guides/ubuntu/ubuntu-focal.html

### ISSUE THREAD

**Issue by BLiTyvr** [intel-gpu/documentation#11]
There is a **403 Forbidden** error when attempting to access the repository:

root@ubuntu02:/etc# apt-add-repository 'deb https://repositories.intel.com/graphics/ubuntu focal main'
Repository: 'deb https://repositories.intel.com/graphics/ubuntu focal main'
Description:
Archive for codename: focal components: main
More info: https://repositories.intel.com/graphics/ubuntu
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/archive_uri-https_repositories_intel_com_graphics_ubuntu-groovy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-https_repositories_intel_com_graphics_ubuntu-groovy.list
Hit:1 http://ca.archive.ubuntu.com/ubuntu groovy InRelease
**Err:2 https://repositories.intel.com/graphics/ubuntu groovy InRelease
  403  Forbidden [IP: 13.224.10.76 443]**
Hit:3 http://ca.archive.ubuntu.com/ubuntu groovy-updates InRelease
Get:4 https://repositories.intel.com/graphics/ubuntu focal InRelease [3195 B]
Hit:5 http://ca.archive.ubuntu.com/ubuntu groovy-backports InRelease
Hit:6 http://ca.archive.ubuntu.com/ubuntu groovy-security InRelease
Get:7 https://repositories.intel.com/graphics/ubuntu focal/main amd64 Packages [108 kB]
Reading package lists... Done   
**E: Failed to fetch https://repositories.intel.com/graphics/ubuntu/dists/groovy/InRelease  403  Forbidden [IP: 13.224.10.76 443]**
E: The repository 'https://repositories.intel.com/graphics/ubuntu groovy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by jketreno** [comment]
The repositories only support Ubuntu 20.04 (Focal) however when you've added it it looks like your system is changing it from 'focal' to 'groovy'

I don't know if there is an apt-add-repository flag to tell it not to change the repo path when it installs the repository.

You could try editing /etc/apt/sources.list.d/archive_uri-https_repositories_intel_com_graphics_ubuntu-groovy.list and change "groovy" to "focal" that might work.

**Comment by pepla** [comment]
Hi @BLiTyvr  - were you able to follow up on previous suggestions? Let us know if you were able to resolve your issue or further help is needed.

**Comment by pepla** [comment]
@BLiTyvr I will close this issue now as inactive. Let us know if you will need further assistance.
