### ISSUE TITLE
Feedback on installation-guides/ubuntu/ubuntu-focal.html

### ISSUE THREAD

**Issue by androniychuk** [intel-gpu/documentation#12]
The following package is needed to add a repository to apt
software-properties-common

It is not specified in the docs page
https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html

**Comment by ketrintel** [comment]
software-properties-common is a required dependency of cloud-init, ubuntu-server, and ubuntu-desktop so to have a loaded Ubuntu system, you should have software-properties-common installed already. We try and keep the list of prerequisites to only be those which wouldn't already be installed in one of the common base OS flavors.

Which base flavor did you use that didn't have software-properties-common preinstalled?

Thanks,
James

**Comment by pepla** [comment]
Hi @androniychuk - can you please let us know if this is still valid problem or provided comments clarified current situation?

**Comment by androniychuk** [comment]
I believe I tested within a container.
If in some flavors its included but not in others, its safest to include it in the list as its unknown.

**Comment by pepla** [comment]
@androniychuk are you able to see this issue with fresh image installation? I do not see this missing on my side and also it is there during internal testing. 
Do you still see this as valid problem?

**Comment by androniychuk** [comment]
If issue is not reproduceable then you can close.

**Comment by pepla** [comment]
Thanks, Closing.
