### ISSUE TITLE
403  Forbidden

### ISSUE THREAD

**Issue by UpTheIrons** [intel-gpu/documentation#13]
Intel Graphics Repo is giving forbidden access under ubuntu hirsute, despite it's repo is set as focal instead due to no hirsute repo.

**Comment by ketrintel** [comment]
Can you paste the console output during the apt update / apt install so we can see which URLs it is trying to hit on the server?

Thanks,
James

**Comment by UpTheIrons** [comment]
Good afternoon,
Follows as request, attempted Grovvy & Hirsute instead of focall, same issue:

Lendo listas de pacotes...
Construindo árvore de dependências...
Lendo informação de estado...
Lendo informações estendidas de estado...
Inicializando estados de pacotes...
Escrevendo informações estendidas de estado...
Construindo o banco de dados de tags...
Os pacotes a seguir serão atualizados:
  intel-media-va-driver-non-free libmfx1 libva-drm2 libva-wayland2 libva-x11-2 libva2 
6 pacotes atualizados, 0 novos instalados, 0 a serem removidos e 0 não atualizados.
É preciso obter 8.236 kB de arquivos. Depois do desempacotamento, 11,3 kB serão liberados.
Escrevendo informações estendidas de estado...
Err https://repositories.intel.com/graphics/ubuntu focal/main amd64 libva-x11-2 amd64 2.11.0+i557~u20.04
  403  Forbidden [IP: 13.224.128.98 443]
Err https://repositories.intel.com/graphics/ubuntu focal/main amd64 libva-wayland2 amd64 2.11.0+i557~u20.04
  403  Forbidden [IP: 13.224.128.98 443]
Err https://repositories.intel.com/graphics/ubuntu focal/main amd64 libva-drm2 amd64 2.11.0+i557~u20.04
  403  Forbidden [IP: 13.224.128.98 443]
Err https://repositories.intel.com/graphics/ubuntu focal/main amd64 libva2 amd64 2.11.0+i557~u20.04
  403  Forbidden [IP: 13.224.128.98 443]
Err https://repositories.intel.com/graphics/ubuntu focal/main amd64 intel-media-va-driver-non-free amd64 21.2.0+i557~u20.04
  403  Forbidden [IP: 13.224.128.98 443]
Err https://repositories.intel.com/graphics/ubuntu focal/main amd64 libmfx1 amd64 21.2.0+i557~u20.04
  403  Forbidden [IP: 13.224.128.98 443]
Lendo listas de pacotes...
Construindo árvore de dependências...
Lendo informação de estado...
Lendo informações estendidas de estado...
Inicializando estados de pacotes...
Escrevendo informações estendidas de estado...
Construindo o banco de dados de tags...

**Comment by ketrintel** [comment]
Ah; this looks like the problem we've periodically been seeing due to packages having a "+" in their filename. We're still working on a long term fix for the repository.

As a temporary work around you can try this https://github.com/intel-gpu/documentation/issues/9#issuecomment-817185937:

```bash
apt-get install --print-uris \
  intel-opencl-icd \
  intel-level-zero-gpu level-zero \
  intel-media-va-driver-non-free libmfx1 \
    | awk -F\' '/https/{print $2}' \
    | sed 's/\+/%2B/g' \
    | xargs sudo wget -P /var/cache/apt/archives \
    && sudo apt-get install \
      intel-opencl-icd \
      intel-level-zero-gpu level-zero \
      intel-media-va-driver-non-free libmfx1
```

**Comment by UpTheIrons** [comment]
Thanks a lot!

Em sex., 11 de jun. de 2021 às 14:14, James ***@***.***>
escreveu:
