### ISSUE TITLE
Feedback on index.html

### ISSUE THREAD

**Issue by zhiweiw88** [intel-gpu/documentation#15]
There are instructions on the following OS:

    Red Hat* 8.3
    Red Hat* 8.2
    Red Hat* 8.1
    SUSE* 15 SP2
    SUSE* 15 SP1
    Ubuntu* 20.04 (focal)
    Ubuntu* 18.04 (bionic)

Our system is CentOS-based. Could you also provide the instructions on CentOS?

**Comment by pepla** [comment]
Hi @zhiweiw88 ,

Thank you for your valuable comment! 

The reason why we don't list CentOS on our official page is that we do not fully validate on that OS version and so do not list instructions specific for that OS. Nevertheless, as CentOS is known derivative from RHEL, we do strive to maintain compatibility and functionality with CentOS. We have heard from several users that the packages we provide for RHEL do work as expected on CentOS when following the instructions provided for RHEL.

**Comment by pepla** [comment]
Closing as distro support was clarified.
