### ISSUE TITLE
Feedback on technologies/level-zero.html

### ISSUE THREAD

**Issue by aditikau** [intel-gpu/documentation#16]
**Ubuntu 20.04**
Install the development repository "Ubuntu 20.04" and then install the Level Zero packages:

This URL to Ubuntu 20.04 is not working. 
https://dgpu-docs.intel.com/technologies/level-zero.html

**Comment by pepla** [comment]
@aditikau Thanks for your valuable feedback! Link fix has been submitted and should be available soon.

**Comment by pepla** [comment]
Fix was posted to: https://dgpu-docs.intel.com/
