### ISSUE TITLE
Link not working - installation-guides/ubuntu/ubuntu-focal.html

### ISSUE THREAD

**Issue by aditikau** [intel-gpu/documentation#17]
https://repositories.intel.com/graphics/ubuntu 
This link not working.
![image](https://user-images.githubusercontent.com/74347383/124901994-23ca1480-e000-11eb-9d86-f2925df23b86.png)

**Comment by pepla** [comment]
Hi @aditikau,

Thanks for your comment but unfortunately it is expected behavior. Repositories.intel.com are not indexed and cannot be search via web browser. Please use  guidelines as described on https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html

**Comment by pepla** [comment]
Closing as expected behavior.
