### ISSUE TITLE
Feedback on installation-guides/redhat/redhat-8.4.html

### ISSUE THREAD

**Issue by mshabunin** [intel-gpu/documentation#19]
Proposed command `sudo dnf update --refresh` will _upgrade_ all packages in the system (see https://dnf.readthedocs.io/en/latest/command_ref.html#upgrade-command-label). I think this behavior is wrong, if you want to force synchronization with reposity servers you should add `--refresh` option to `dnf install` call.

Same comment is applicable to all RedHat documentation pages.

**Comment by mshabunin** [comment]
**cc** @artanokhov

**Comment by pepla** [comment]
Change discussed internally and accepted. PR submitted: https://gitlab.devtools.intel.com/vtt/sws/osgc/gpgpu/-/merge_requests/33

**Comment by pepla** [comment]
Updated and merged. Closing the ticket.
