### ISSUE TITLE
Feedback on /installation-guides/ubuntu/ubuntu-focal.html

### ISSUE THREAD

**Issue by FarshadAkhbari** [intel-gpu/documentation#2]
In adding the repo stage, I am getting an error message which needs to be addressed:

$ sudo apt-add-repository   'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main'

Ign:1 https://repositories.intel.com/graphics/ubuntu focal InRelease
Ign:2 https://apt.repos.intel.com/oneapi all InRelease
Err:3 https://apt.repos.intel.com/oneapi all Release
  Could not handshake: The TLS connection was non-properly terminated. [IP: 10.1.192.48 912]
Err:4 https://repositories.intel.com/graphics/ubuntu focal Release
  Could not handshake: The TLS connection was non-properly terminated. [IP: 10.1.192.48 912]
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:6 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:7 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Reading package lists... Done

Snipping the rest of the log…

The normal proxy to access internal servers is 911. But to see if I can please the tool, I changed my proxy server to 912. But I am still getting the same error. I tried to ping the ip address 10.1.192.48 and DO NOT get any response back. Without access to these nodes, I can’t download either of the level-zero drivers. Please update this page with correct information or guide me through any environment issue causing these errors.

**Comment by ketrintel** [comment]
It looks like you are trying to install from behind a corporate firewall; you need to configure your system to access repositories.intel.com from outside of the firewall via a proxy.

10.1.192.48 is not an IP address registered for repositories.intel.com:

```bash
$ host repositories.intel.com
repositories.intel.com is an alias for repositories.osgc.infra-host.com.
repositories.osgc.infra-host.com has address 13.224.2.105
repositories.osgc.infra-host.com has address 13.224.2.114
repositories.osgc.infra-host.com has address 13.224.2.22
repositories.osgc.infra-host.com has address 13.224.2.108
```

**Comment by FarshadAkhbari** [comment]
I do this when I am inside Intel network. What needs to happen for this access mode to work?


Regards,
Farshad.

On Jan 14, 2021, at 3:43 PM, James <notifications@github.com> wrote:

﻿

It looks like you are trying to install from behind a corporate firewall; you need to configure your system to access repositories.intel.com from outside of the firewall via a proxy.

10.1.192.48 is not an IP address registered for repositories.intel.com:

$ host repositories.intel.com
repositories.intel.com is an alias for repositories.osgc.infra-host.com.
repositories.osgc.infra-host.com has address 13.224.2.105
repositories.osgc.infra-host.com has address 13.224.2.114
repositories.osgc.infra-host.com has address 13.224.2.22
repositories.osgc.infra-host.com has address 13.224.2.108

**Comment by jketreno** [comment]
Verified FQDN is working correctly and this was a system configuration issue; closing.
