### ISSUE TITLE
Quesition installation-guides/ubuntu/ubuntu-focal.html

### ISSUE THREAD

**Issue by yeonbok** [intel-gpu/documentation#23]
Hello, 
I tried to follow this guide: https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html
But I could not add repository 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main'
by connection timeout.

: Failed to fetch https://repositories.intel.com/graphics/ubuntu/dists/focal/InRelease  Could not connect to repositories.intel.com:443 (54.230.114.55), connection timed out Could not connect to repositories.intel.com:443 (54.230.114.20), connection timed out Could not connect to repositories.intel.com:443 (54.230.114.126), connection timed out Could not connect to repositories.intel.com:443 (54.230.114.91), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.

Could  I get what will be the solution? Thanks!

**Comment by pepla** [comment]
Hi @yeonbok !

Are you trying to execute those command from Intel internal network or outside? If it is happening internally at intel it is simple proxy settings issue. You can try instructions provided on internal page: https://agama.jf.intel.com/internal

**Comment by yeonbok** [comment]
Ah yes it was due to the intel proxy. I could access that from external network. Thank you!
