### ISSUE TITLE
No second VGA compatible controller.

### ISSUE THREAD

**Issue by Soldy** [intel-gpu/documentation#25]
Hello!

I followed this documentation: https://dgpu-docs.intel.com/devices/iris-xe-max-graphics/index.html
My issues I have no second  ```VGA compatible controller [0300]: Intel Corporation Device [8086:4905] (rev 01) ```  after the reboot.
Here is my  cpuinfo, dmesg kernel config, lspci.
[cpuinfo.txt](https://github.com/intel-gpu/documentation/files/7403246/cpuinfo.txt)
[dmesg.txt](https://github.com/intel-gpu/documentation/files/7403247/dmesg.txt)
[kernel.config.txt](https://github.com/intel-gpu/documentation/files/7403248/kernel.config.txt)
[lspci.txt](https://github.com/intel-gpu/documentation/files/7403249/lspci.txt)

I missed something?

**Comment by bouachalazhar** [comment]
> Solved with pci pf stub

I have the same problem check this [link ](https://github.com/intel-gpu/documentation/issues/76#issue-1655635305) please, thanks !
