### ISSUE TITLE
Feedback on index.html

### ISSUE THREAD

**Issue by castlejune** [intel-gpu/documentation#27]
flickering screen with Intel Hd graphics

**Comment by castlejune** [comment]
exactly my laptop is dell 7490 with intel UHD 620 graphics. I did try different linux distros but to no avail always this FLICKERING SCREEN problem!  Pls. I need Your help. thanks

**Comment by rodrigovivi** [comment]
I'm afraid this is the wrong place to report bugs. 
Please follow https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs and report to:
https://gitlab.freedesktop.org/drm/intel/-/issues
