### ISSUE TITLE
Feedback on installation-guides/ubuntu/ubuntu-focal.html

### ISSUE THREAD

**Issue by Apogeum12** [intel-gpu/documentation#28]
### For all version greater than 20.2.0+i374~u20.04 don't work hardware accelerate video for chromium.

Example when work:
```bash
   System: Ubuntu 20.04.3 LTS x86_64
   Mesa: 21.1.6
   Chromium bassed(Brave):  Brave | 1.32.113 Chromium: 96.0.4664.45
   intel-media-va-driver-non-free/focal,now 20.2.0+i374~u20.04 amd64 
```
Example when don't work:
```bash
   System: Ubuntu 20.04.3 LTS x86_64
   Mesa: 21.1.6
   Chromium bassed(Brave):  Brave | 1.32.113 Chromium: 96.0.4664.45
   intel-media-va-driver-non-free/focal,now  (all > 20.2.0+i374~u20.04)
```
List don't work `intel-media-va-driver-non-free` drive
![intel_ver](https://user-images.githubusercontent.com/35242996/143771747-f3614c71-8179-4799-9576-21db9d41fe91.png)

**Comment by rodrigovivi** [comment]
Please follow the steps described in https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs and report the bug at https://gitlab.freedesktop.org/drm/intel/-/issues
Thanks,
Rodrigo.
