### ISSUE TITLE
Ubuntu 22.04 LTS Jammy based repos?

### ISSUE THREAD

**Issue by Joshndroid** [intel-gpu/documentation#44]
I have a looked through your documentation with the ubuntu install guides.
there is no jammy 22.04 repo listed.
I figured if the docs were yet to be updated and just tried replace 'focal' with 'jammy' however the repo is not signed.

`sudo apt-add-repository deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu jammy main'`

once apt update was run I got,

```
E: Failed to fetch https://repositories.intel.com/graphics/ubuntu/dists/jammy/InRelease  403  Forbidden [IP: 108.139.1.66 443]
E: The repository 'https://repositories.intel.com/graphics/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I had added the key in the initial line with

`wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | sudo apt-key add -`

which did talk about apt-key being deprecated but it still listed as being 'OK' ie added.

**Comment by ChenKej1e** [comment]
Hi @Joshndroid , the repository for Ubuntu 22.04 has not been released yet. We will release the jammy repo soon.

**Comment by Joshndroid** [comment]
thanks @ChenKej1e for the reply. 
I am eagerly awaiting the repos as I have a few devices which are hurting with no igpu support at present. (4k video playback kinda sucky)

**Comment by eero-t** [comment]
Jammy repository is there, documented for Arc: https://dgpu-docs.intel.com/installation-guides/index.html

**Comment by Joshndroid** [comment]
Eyyyy... it's up... thanks intel-gpu team
