### ISSUE TITLE
Feedback on index.html

### ISSUE THREAD

**Issue by zx1987** [intel-gpu/documentation#5]
Dear Intel Developer Team,

I am trying out the oneAPI product, and was required to install the GPGPU package. My system is redhat 7.9 but seems like the GPGPU only supports 8.1 or 8.2. Do you have any suggestions for to work around this? Thank you.
Best,
Xiang

**Comment by ketrintel** [comment]
Thank you for reaching out. Unfortunately, we do not publish package repositories for Red Hat 7.x. To use the packages documented on dgpu-docs.intel.com with oneAPI, you will need to be using Red Hat 8.x or newer.

I haven’t tried it myself, but you could try running the oneAPI packages and RHEL 8 GPGPU packages in a container on RHEL 7. This blog gives information on setting up a RHEL 8 container on RHEL 7: https://developers.redhat.com/blog/2019/08/23/run-red-hat-enterprise-linux-8-in-a-container-on-rhel-7/

**Comment by yang-dl** [comment]
How do I install this on a debian linux?

**Comment by yang-dl** [comment]
When I installed on Debian using the ubuntu installation method, a gpg error was reported when apt update

**Comment by pepla** [comment]
@yang-dl  can you please provide more information about the error observed? Let me know if you are still seeing this issue and pleas provide information about distro version.

**Comment by pepla** [comment]
@yang-dl  I will close this issue now as inactive. Let us know if you will need further assistance.
