### ISSUE TITLE
Feedback on installation-guides/ubuntu/ubuntu-focal.html

### ISSUE THREAD

**Issue by madbombus** [intel-gpu/documentation#6]
wget -qO - https://repositories.intel.com/graphics/intel-graphics.key |
  sudo apt-key add -
Should be written as single line, current version does not work

**Comment by jketreno** [comment]
Thank you for taking the time to reach out.

Which shell are you using? In sh and bash, the pipe at the end of the wget line will continue parsing into the next line.

In general, we try and style the copy/paste able content with line-wraps set to an ~80 character console width so when viewed on smaller displays, via links in a terminal, or as [raw text](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.txt), the reader can view the full command line without scrolling.

**Comment by pepla** [comment]
Hi @madbombus  - can you please let us know if comment above was useful? Can we consider this issue as closed now?

**Comment by pepla** [comment]
@madbombus I will close this issue now as inactive. Let us know if you will need further assistance.
