### ISSUE TITLE
Driver installation failed after initial success

### ISSUE THREAD

**Issue by mliu2020** [intel-gpu/documentation#61]
Hi,

I have a Data Center Flex card on a Xeon platform with Ubuntu20.04, I went through the installation by following the official instruction:
https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal-dc.html
I was successful for a couple weeks and it started failed from last Friday.

The installation process seems OK but I can't get the devices:
~# ls /dev/dri/render*
ls: cannot access '/dev/dri/render*': No such file or directory

Can you help me how to debug?

Mark

**Comment by alexzuointel** [comment]
please help to collect the logs with
https://dgpu-docs.intel.com/Q%26A/Q%26A.html#how-to-report-an-issue 

thanks.

**Comment by mliu2020** [comment]
Thanks so much for the quick response,

Attached the logs I collected when the issue happened.
[atsm_log.zip](https://github.com/intel-gpu/documentation/files/10024045/atsm_log.zip)

Mark

**Comment by mliu2020** [comment]
Thanks so much for the support, this issue is solved.
