### ISSUE TITLE
[ThinkPad P16] HDMI port on ThinkPad TBT4 Dock does not work properly.

### ISSUE THREAD

**Issue by jendrina69** [intel-gpu/documentation#73]
We have successfully installed the Intel driver as instructed here https://dgpu-docs.intel.com/installation-guides/index.html. We did basic testing and found out that the HDMI port on the ThinkPad TBT4 Dock does not work. When the external monitor is connected thru the TBT4 dock’s HDMI port, the display is not detected properly, black screen or hangs up. The same system and dock is verified OK on Windows 10 and on similar system with Nvidia GPU(with Ubuntu 22.04 OS). It is also OK if connected directly on the system’s HDMI port.

Steps to reproduce:
1.	Install Ubuntu 22.04 oem on ThinkPad P16 system.
2.	Install Intel driver.
3.	Verify the installation is OK.
4.	Connect ThinkPad TBT4 Dock.
5.	Connect external monitor to the dock’s HDMI port. --> problem

Actual Result: The display is not detected properly, black screen or system hangs up.
Expected Result: External monitor connected thru TBT4 dock’s HDMI port can display normally.

System: ThinkPad P16
BIOS: N3FET32W (1.17)
EC: N3FHT19W (1.07)
OS: Ubuntu 22.04.1 LTS
Kernel: 5.17.0.1019-oem
Display Adapter:
   Intel(R) Arc(TM) Pro A30M Graphics
   Intel(R) UHD Graphics
External Monitor1: Asus PA27AC
Dock: ThinkPad TBT4 Dock(Pionner11)

The dmesg was flooded with pcieport events that seems to have overwritten the earlier part of the log. However, we captured journalctl, hope this contain some helpful information. Please see attached files. 
[journal.log](https://github.com/intel-gpu/documentation/files/10800907/journal.log)
[kernel.log](https://github.com/intel-gpu/documentation/files/10800910/kernel.log)

**Comment by YangShi-Intel** [comment]
@jendrina69   Two questions:
1. Is this issue only happened with TBT4 dock?  
If you connect the HDMI directly to the HDMI port of notebook, what about the test result?

2.  Would you like to provide the xorg.log.  
It should be under dir: /var/log/Xorg.0.log

**Comment by jendrina69** [comment]
Is this issue only happened with TBT4 dock?
<jendrina69> Yes
If you connect the HDMI directly to the HDMI port of notebook, what about the test result?
<jendrina69> External display is OK.

Would you like to provide the xorg.log.
It should be under dir: /var/log/Xorg.0.log
<jendrina69> Please see attached file.
[Xorg.0.log](https://github.com/intel-gpu/documentation/files/10801621/Xorg.0.log)

**Comment by YangShi-Intel** [comment]
@jendrina69  There should be two inode under /sys/kernel/debug/dri/
Please collect following logs:
Plug HDMI directly to the HDMI port of notebook,  collect: 
/sys/kernel/debug/dri/0/i915_display_info
/sys/kernel/debug/dri/1/i915_display_info

Plug HDMI to TBT4 dock, collect:
/sys/kernel/debug/dri/0/i915_display_info
/sys/kernel/debug/dri/1/i915_display_info

**Comment by jendrina69** [comment]
@YangShi-Intel 
Please see attached logs.

Plug HDMI directly to the HDMI port of notebook
[i915_display_info_0_hdmi_direct.log](https://github.com/intel-gpu/documentation/files/10822301/i915_display_info_0_hdmi_direct.log)
[i915_display_info_1_hdmi_direct.log](https://github.com/intel-gpu/documentation/files/10822306/i915_display_info_1_hdmi_direct.log)

Plug HDMI to TBT4 dock
[i915_display_info_0_hdmi_dock.log](https://github.com/intel-gpu/documentation/files/10822312/i915_display_info_0_hdmi_dock.log)
[i915_display_info_1_hdmi_dock.log](https://github.com/intel-gpu/documentation/files/10822320/i915_display_info_1_hdmi_dock.log)

**Comment by YangShi-Intel** [comment]
@jendrina69  
1. 
sudo vim /etc/default/grub    drm.debug=0x1e add this into linux cmdline.
sudo update-grub
sudo reboot
catch the full dmesg log when plug HDMI to TBT4 dock.


2. Would you like to try this issue on TBT3 dock?  I didn't reproduce this issue on TBT3 dock, but my DG2 notebook is not exactly the same as yours.

**Comment by jendrina69** [comment]
@YangShi-Intel 
This is the weird part, the problem does not occur when "drm.debug=0x1e log_buf_len=4M"  parameter is entered in the kernel command line. Please see attached dmesg.
[dmesg_drmdbg_0x1e_Feb24.log](https://github.com/intel-gpu/documentation/files/10822670/dmesg_drmdbg_0x1e_Feb24.log)

**Comment by YangShi-Intel** [comment]
@jendrina69  Would you like to try this issue on TBT3 dock?  Thanks

**Comment by jendrina69** [comment]
@YangShi-Intel 
The problem could not be reproduced on ThinkPad TBT3 Dock with or without the "drm.debug=0x1e log_buf_len=4M" kernel parameter. Please see attached dmesg.
[dmesg_TBT3_drmdbg.log](https://github.com/intel-gpu/documentation/files/10836980/dmesg_TBT3_drmdbg.log)

**Comment by YangShi-Intel** [comment]
@jendrina69  Would you like to try drm.debug=0x11e  ?
Please test it for more than 10 times, maybe we can catch the full log when this issue is reproduced.  Thanks

**Comment by jendrina69** [comment]
@YangShi-Intel 
We updated the kernel to 6.1.0-1007-oem and this problem could no longer be reproduced.
